// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://limvajcxxkgleztxrqpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbXZhamN4eGtnbGV6dHhycXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNjI5OTQsImV4cCI6MjA3NzczODk5NH0.R4ST3ooXzomnHUORGZPArufEqJm0kvVW7w5vYcOgJt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});